name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ TEST_SECRET_MJ }}
          USERNAME: ${{ MinChoi0129 }}
      - name: Commit & Push
        run: |
          git config MinChoi0129 github-actions
          git config wjdchs0129@gnu.ac.kr github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
